<script lang="ts">
	import { onMount } from 'svelte';
	import { resolve as svelteResolve } from '$app/paths';

	type PagefindResult = {
		url: string;
		excerpt?: string;
		meta?: {
			title?: string;
			section?: string;
			description?: string;
		};
	};

	type PagefindModule = {
		search: (query: string) => Promise<{
			results: Array<{ data: () => Promise<PagefindResult> }>;
		}>;
		options?: (options: { excerptLength: number }) => Promise<void>;
	};

	let query = $state('');
	let results = $state<PagefindResult[]>([]);
	let pagefind = $state<PagefindModule | null>(null);
	let isLoading = $state(true);
	let isSearching = $state(false);
	let hasError = $state(false);
	let debounceTimer: ReturnType<typeof setTimeout> | undefined;

	onMount(async () => {
		try {
			// Generated by scripts/build-pagefind.mjs and served from static/pagefind.
			const pagefindUrl = ['/pagefind', 'pagefind.js'].join('/');
			pagefind = (await import(/* @vite-ignore */ pagefindUrl)) as PagefindModule;
			await pagefind.options?.({ excerptLength: 24 });
		} catch {
			hasError = true;
		} finally {
			isLoading = false;
		}
	});

	const resolve = svelteResolve as unknown as (path: string) => string;

	const runSearch = async (value: string) => {
		const normalized = value.trim();
		if (!pagefind || normalized.length < 2) {
			results = [];
			return;
		}

		isSearching = true;
		try {
			const response = await pagefind.search(normalized);
			results = await Promise.all(response.results.slice(0, 8).map((result) => result.data()));
		} catch {
			hasError = true;
			results = [];
		} finally {
			isSearching = false;
		}
	};

	const handleInput = (event: Event) => {
		query = (event.currentTarget as HTMLInputElement).value;
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => runSearch(query), 180);
	};
</script>

<section class="docs-search" aria-label="Search documentation">
	<label for="docs-search-input">Search the library</label>
	<div class="docs-search-control">
		<input
			id="docs-search-input"
			class="input"
			type="search"
			placeholder="Search title or document content"
			value={query}
			oninput={handleInput}
			aria-describedby="docs-search-status"
		/>
		{#if query}
			<button
				class="is-icon docs-search-clear"
				type="button"
				aria-label="Clear search"
				onclick={() => {
					query = '';
					results = [];
				}}
			>
				×
			</button>
		{/if}
	</div>

	<p id="docs-search-status" class="docs-search-status" aria-live="polite">
		{#if isLoading}
			Loading search…
		{:else if isSearching}
			Searching…
		{:else if hasError}
			Search is unavailable until the Pagefind index is generated.
		{:else if query.trim().length >= 2}
			{results.length} result{results.length === 1 ? '' : 's'}
		{:else}
			Search by title or content.
		{/if}
	</p>

	{#if results.length}
		<div class="docs-search-results">
			{#each results as result (result.url)}
				<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -->
				<a class="docs-search-result" href={resolve(result.url)}>
					<strong>{result.meta?.title || 'Untitled document'}</strong>
					{#if result.meta?.section}<span>{result.meta.section}</span>{/if}
					{#if result.excerpt}
						<!-- Pagefind generates this excerpt and its mark tags. -->
						<!-- eslint-disable-next-line svelte/no-at-html-tags -->
						<p>{@html result.excerpt}</p>
					{/if}
				</a>
			{/each}
		</div>
	{/if}
</section>
